#!/bin/sh
":" //;NODE_PATH=$(npm -g root) exec node -r $(dirname $0)/sideLoad.js -- "$0" "$@"
const usage = `Takes the cookies from a working xhr call in browser and sets up hosted Jira instances.
BE SURE TO WRAP THE COOKIE IN QUOTES!`;
const argv = require('yargs')
  .usage(`$0 "<cookie>" # ${usage}`)
  .alias('help', 'h')
  .example( 'jiraCookie "atlassian.xsrf.token=blah; JSESSIONID=blah; SESSIONCOOKIE=SessionCookie; LOGOUTCOOKIE=blah; SAMLCOOKIE=blah"')
  .argv;
const inquirer = require('inquirer');
const {execSync, spawn} = require('child_process');
const fs = require('fs').promises;
const HOME = require('os').homedir();

(async () => {
  const cookiesFile = `${HOME}/.jira.d/cookies.js`;
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  let newCookies = argv._[0]
    .split(';')
    .map(item => item.trim())
    .map(keyval => {
      const cookie = keyval.split('=');
      return {
        Name: cookie[0],
        Value: cookie[1].replace(/"/g,''),
        Domain:process.env.JIRA_S_ENDPOINT,
        Expires: tomorrow.toISOString(),
        HostOnly: true,
        HttpOnly: false,
        Path: '/',
        Secure: false,
        Raw: keyval,
      };
    });
  const finalCookies = JSON.stringify(newCookies)
  await fs.writeFile(cookiesFile, finalCookies);
})();

// vim: ft=javascript
