#!/bin/sh
usage="$(basename "$0") Resets working branch, switches to either master or provided branch, and pulls."

while getopts ':h' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
  esac
done

BRANCH=master
if [ -n "$1" ] ; then
  BRANCH="$1"
fi
git reset --hard
git checkout "$BRANCH"
git pull
