#!/bin/sh
usage="$(basename "$0") [-hr] Resets working branch, switches to either master or provided branch, pulls, switches back and \
starts merge.
  -r Runs rebase instead of merge"

while getopts ':hr' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    r) rebase="true"
       ;;
  esac
done
shift $((OPTIND -1))

current=$(git branch | grep \* | cut -d ' ' -f2)
BRANCH=master
if [ -n "$1" ] ; then
  BRANCH="$1"
fi
git reset --hard
git checkout "$BRANCH"
git pull
git checkout $current
if [ -n "$rebase" ] ; then
  git rebase "$BRANCH"
else
  git merge "$BRANCH"
fi

git mergetool
find . -type f -name "*.orig" -exec mv {} /tmp/ \;
echo ".orig files moved to /tmp"
