#!/bin/zsh

usage="$(basename "$0") -fh uses aws-cli to monitor the codepipeline status of \$AWS_JOBS_LIST.
Requirments:
jq and aws-cli installed
\$AWS_PIPELINE_PROFILE be set to appropriate argument to --profile option of aws-cli
and either
\$AWS_JOBS_LIST be set as an array which contains the jobs to monitor (ZSH)
or
\$--file FILE provided which contains the jobs to monitor, one per line (other shells)

Additionally, user must be authenticated with aws (e.g., via .aws/config)."
# Requirements: aws-cli, jq

# JQ partials

getFailedAction='[.actionStates[] | select( .latestExecution.status != "Succeeded")][0]'
printActionStatus='[35m\(.actionName)[0m \(.latestExecution.status)'
checkAndPassLastChange='.latestExecution.lastStatusChange then .latestExecution.lastStatusChange'
awsTimeSinceSecOffsets='split(".")| { offset: (.[1][6:9] | tonumber), sec: (.[0] + "Z" | fromdate) }'
offsetAdjust='now - .sec + ((.offset + 1) * 60 * 60)'
formatMinHour='(. / 60 | floor | tostring) + "m" + (. % 60 | tostring) + "s"'

# Compose filter chain
fullJQ=$(echo '[.stageStates[] | select( .latestExecution.status != "Succeeded")][0] | try ' $getFailedAction \
      ' |"' $printActionStatus ' (\( if ' $checkAndPassLastChange \
        ' | ' $awsTimeSinceSecOffsets ' | ' "$offsetAdjust" ' | ' $formatMinHour \
      ' else ""' \
      ' end))"')

# Get job states
awsjobs () {
  for job in "${AWS_JOBS_LIST[@]}"
  do
    latestNonSuccessful=$( aws codepipeline get-pipeline-state \
      --profile="${AWS_PIPELINE_PROFILE}" \
      --name="${job}" --output=json \
      | jq "$fullJQ"
    )
    latestNonSuccessful="${latestNonSuccessful%\"}"
    latestNonSuccessful="${latestNonSuccessful#\"}"
    if [ -z "$latestNonSuccessful" ]; then
      echo -n "✅ [38;5;000;48;5;040m$job[0m"
    elif [[ "$latestNonSuccessful" == *"Failed"* ]]; then
      echo -n "❌ [38;5;000;48;5;009m$job[0m: $latestNonSuccessful"
    else
      echo -n "⛴  [38;5;000;48;5;226m$job[0m: $latestNonSuccessful"
    fi
    tput el
    echo
  done
}

if [ -z "$AWS_JOBS_LIST" ] || [ ${#AWS_JOBS_LIST[@]} -eq 0 ]; then
  if [[ "$1" == *"-f"* ]] && [ -n "$2" ]; then
    echo "a file"
    SAVEIFS=$IFS
    IFS=$'\n'
    AWS_JOBS_LIST=$(< "$2")
    AWS_JOBS_LIST=($AWS_JOBS_LIST)
    IFS=$SAVEIFS
    echo "$AWS_JOBS_LIST"
  else
    echo "No jobs listed provided"
    echo "$usage"
    exit
  fi
fi

if [ -z "$AWS_PIPELINE_PROFILE" ]; then
  echo "AWS_PIPELINE_PROFILE not set"
  echo "$usage"
  exit
fi

if [[ "$1" == *"-h"* ]]; then
  echo "$usage"
  exit
fi

clear
while true;
do
  awsjobs
  tput ed || tput cd
  sleep 20
  tput home
done
